# Generated by Django 4.0.6 on 2022-08-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_description_alter_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
